name: Build APK with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Check Gradle Wrapper files
      run: |
        echo "Checking Gradle Wrapper files..."
        ls -la gradlew*
        ls -la gradle/wrapper/
        echo "gradlew file exists: $(test -f gradlew && echo 'YES' || echo 'NO')"
        echo "gradlew.bat file exists: $(test -f gradlew.bat && echo 'YES' || echo 'NO')"
        echo "gradle-wrapper.jar exists: $(test -f gradle/wrapper/gradle-wrapper.jar && echo 'YES' || echo 'NO')"
        
    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        ls -la gradlew
        file gradlew
        echo "gradlew is executable: $(test -x gradlew && echo 'YES' || echo 'NO')"
        
    - name: Validate Gradle Wrapper
      run: |
        ./gradlew --version
        ./gradlew --help
        
    - name: Build APK with Gradle
      run: ./gradlew assembleRelease --no-daemon --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
